### ISSUE TITLE
Unexpected token ILLEGAL - reEmptyStringMiddle =

### ISSUE THREAD

**Issue by ghost** [aurelia/app-contacts#19]
Hi,

Just downloaded and tried to play with it.

Unfortunately, after a couple of warning while running "npm install", `gulp watch` ends up with the following error:

```
ilema@minix /files/dev/wspace_web/app-contacts-0.3.0 > gulp watch
/files/dev/wspace_web/app-contacts-0.3.0/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:45
  reEmptyStringMiddle = 

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/files/dev/wspace_web/app-contacts-0.3.0/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
ilema@minix /files/dev/wspace_web/app-contacts-0.3.0 >
```

As mentioned, these are the warnings:

```
ilema@minix /files/dev/wspace_web/app-contacts-0.3.0 > npm install
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/karma/node_modules/http-proxy requires colors@'0.x.x' but will load
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/karma/node_modules/colors,
npm WARN unmet dependency which is version 1.1.2
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/karma/node_modules/chokidar/node_modules/readdirp requires graceful-fs@'~2.0.0' but will load
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/karma/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.8
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/karma/node_modules/chokidar/node_modules/readdirp requires minimatch@'~0.2.12' but will load
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/karma/node_modules/minimatch,
npm WARN unmet dependency which is version 2.0.8
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-parser requires debug@'0.7.4' but will load
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/browser-sync/node_modules/socket.io/node_modules/debug,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client requires debug@'0.7.4' but will load
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/browser-sync/node_modules/socket.io/node_modules/debug,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/gulp-jshint/node_modules/jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency /files/dev/wspace_web/app-contacts-0.3.0/node_modules/gulp-jshint/node_modules/lodash,
npm WARN unmet dependency which is version 3.10.0
ilema@minix /files/dev/wspace_web/app-contacts-0.3.0 >
```

Next days I will try to find time to look into it.

Meanwhile, thank you!

**Comment by EisenbergEffect** [comment]
Definitely not an Aurelia issue. It's either something with node or jspm itself I would imagine. You might try asking in those groups. I haven't seen this specific issue before.
